# Generated by Django 5.1.5 on 2025-01-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Блюдо", "verbose_name_plural": "Блюда"},
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
