# Generated by Django 5.1.5 on 2025-01-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionmethod",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
