# Generated by Django 5.1.5 on 2025-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_dish_options_alter_dish_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.CharField(max_length=100),
        ),
    ]
