# Generated by Django 5.1.5 on 2025-01-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_dish_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="main",
            name="title",
            field=models.TextField(),
        ),
    ]
